// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tictactoe.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace AllianceGames.Sample.TicTacToe.Grpc {
  public static partial class TicTacToeService
  {
    static readonly string __ServiceName = "core.TicTacToeService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData> __Marshaller_core_PlayerData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AllianceGames.Sample.TicTacToe.Grpc.Response> __Marshaller_core_Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AllianceGames.Sample.TicTacToe.Grpc.Response.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::AllianceGames.Sample.TicTacToe.Grpc.Request> __Marshaller_core_Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::AllianceGames.Sample.TicTacToe.Grpc.Request.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData> __Method_GetPlayerData = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetPlayerData",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_core_PlayerData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::AllianceGames.Sample.TicTacToe.Grpc.Response, global::AllianceGames.Sample.TicTacToe.Grpc.Request> __Method_ServerRequests = new grpc::Method<global::AllianceGames.Sample.TicTacToe.Grpc.Response, global::AllianceGames.Sample.TicTacToe.Grpc.Request>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "ServerRequests",
        __Marshaller_core_Response,
        __Marshaller_core_Request);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AllianceGames.Sample.TicTacToe.Grpc.TictactoeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TicTacToeService</summary>
    [grpc::BindServiceMethod(typeof(TicTacToeService), "BindService")]
    public abstract partial class TicTacToeServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetPlayerData(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::IServerStreamWriter<global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task ServerRequests(grpc::IAsyncStreamReader<global::AllianceGames.Sample.TicTacToe.Grpc.Response> requestStream, grpc::IServerStreamWriter<global::AllianceGames.Sample.TicTacToe.Grpc.Request> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TicTacToeService</summary>
    public partial class TicTacToeServiceClient : grpc::ClientBase<TicTacToeServiceClient>
    {
      /// <summary>Creates a new client for TicTacToeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TicTacToeServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TicTacToeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TicTacToeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TicTacToeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TicTacToeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData> GetPlayerData(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetPlayerData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData> GetPlayerData(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetPlayerData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::AllianceGames.Sample.TicTacToe.Grpc.Response, global::AllianceGames.Sample.TicTacToe.Grpc.Request> ServerRequests(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ServerRequests(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::AllianceGames.Sample.TicTacToe.Grpc.Response, global::AllianceGames.Sample.TicTacToe.Grpc.Request> ServerRequests(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_ServerRequests, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TicTacToeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TicTacToeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(TicTacToeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetPlayerData, serviceImpl.GetPlayerData)
          .AddMethod(__Method_ServerRequests, serviceImpl.ServerRequests).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TicTacToeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetPlayerData, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::AllianceGames.Sample.TicTacToe.Grpc.PlayerData>(serviceImpl.GetPlayerData));
      serviceBinder.AddMethod(__Method_ServerRequests, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::AllianceGames.Sample.TicTacToe.Grpc.Response, global::AllianceGames.Sample.TicTacToe.Grpc.Request>(serviceImpl.ServerRequests));
    }

  }
}
#endregion
