version: '3.3'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: ttt_postgres
    restart: always
    ports:
      - 5452:5432
    environment:
      POSTGRES_INITDB_ARGS: --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
      POSTGRES_PASSWORD: postchain

  blockchain:
    image: "registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:${CHR_CLI_VERSION}"
    container_name: ttt_chromia
    restart: always
    command: chr node start
    ports:
      - 7741:7740
    depends_on:
      - postgres
    volumes:
      - ./rell:/usr/app
    environment:
      CHR_DB_URL: jdbc:postgresql://postgres/postchain

  blockchain_update:
    image: "registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:${CHR_CLI_VERSION}"
    container_name: ttt_chromia_update
    command: chr node update
    depends_on:
      - postgres
    volumes:
      - ./rell:/usr/app
    environment:
      CHR_DB_URL: jdbc:postgresql://postgres/postchain
