version: '3.3'

services:
  matchmaking:
    container_name: matchmaking_service_devnet
    entrypoint: node --enable-source-maps entrypoints/matcher.js local-windows
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      args:
        - GIT_SHA=${GIT_SHA}
    ports:
      - 8090:8080
    restart:  on-failure
    env_file: ".env"
    environment:
      - LOGDIR=${LOGDIR}
      - MATCH_IP_ADDRESS=${MATCH_IP_ADDRESS}
    links:
      - db
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15.3-alpine
    container_name: matchmaking_db_devnet
    restart: always
    # volumes:
    #   - postgres_devnet:/var/lib/postgresql/data
    ports:
      - 5451:5432
    environment:
      POSTGRES_DB: matchmaking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
