version: '3.3'

services:
  ttt_matchmaking:
    container_name: matchmaking_service
    entrypoint: node --enable-source-maps entrypoints/matcher.js ${NETWORK}
    ports:
      - 9085:8080
    build:
      context: .
    restart:  on-failure
    env_file: ".env"
    links:
    - db
    depends_on:
    - db

  db:
    image: postgres:15.3-alpine
    container_name: matchmaking_db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5452:5432
    environment:
      POSTGRES_DB: matchmaking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
    driver: local
