blockchains:
  TicTacToe${APP_SUFFIX}:
    module: ${MAIN_MODULE}

    moduleArgs: &args
      lib.ft4.core.accounts:
        auth_descriptor:
          max_number_per_account: 50
        rate_limit:
          active: true
          max_points: 10
          recovery_time: 5000
          points_at_account_creation: 5
      lib.ft4.core.admin:
        admin_pubkey: ${ADMIN_PUBKEY}
    config:
      gtx:
        modules:
          - "net.postchain.d1.icmf.IcmfReceiverGTXModule"
      sync_ext:
        - "net.postchain.d1.icmf.IcmfReceiverSynchronizationInfrastructureExtension"
      icmf:
        receiver:
          local:
            - bc-rid: x"${AG_BRID}"
              topic: "L_ttt_result"

compile:
  source: src
  target: target
  rellVersion: 0.13.12

libs:
  ft4:
    registry: https://bitbucket.org/chromawallet/ft3-lib
    path: rell/src/lib/ft4
    tagOrBranch: v1.0.0r
    rid: x"FA487D75E63B6B58381F8D71E0700E69BEDEAD3A57D1E6C1A9ABB149FAC9E65F"
    insecure: false
  iccf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/iccf
    tagOrBranch: 1.32.2
    rid: x"1D567580C717B91D2F188A4D786DB1D41501086B155A68303661D25364314A4D"
    insecure: false
  icmf:
    registry: https://gitlab.com/chromaway/core/directory-chain
    path: src/messaging/icmf
    tagOrBranch: 1.32.2
    rid: x"19D6BC28D527E6D2239843608486A84F44EDCD244E253616F13D1C65893F35F6"
    insecure: false
